site_name: Agent Lifecycle Toolkit Documentation
site_url: https://pages.github.com/AgentToolkit/agent-lifecycle-toolkit/


theme:
  name: material
  docs_dir: docs
  features:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime


nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Under the hood:
    - 'Lifecycle': components/lifecycle.md
    - 'ALTK components': components/altk-components-summary.md
    - 'Components':
        - 'Spotlight': components/spotlight.md
        - 'Refraction': components/refraction.md
        - 'SPARC': components/sparc.md
        - 'Silent Review': components/silent-review.md
        - 'JSON Processor': components/json-processor.md
        - 'RAG Repair': components/rag-repair.md
        - 'Policy Guard': components/policy-guard.md
  - Examples: examples.md
  - Integrations: integrations.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AgentToolkit/agent-lifecycle-toolkit/
markdown_extensions:
  - toc:
      permalink: true

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - include-markdown
  - search
