name: Generate Docs
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      deploy:
        type: boolean
        description: "If true, the docs will be deployed"
        default: false

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-python-uv
      - name: Install docs dependencies
        run: uv sync --extra docs
      - name: Build docs
        run: uv run mkdocs build --verbose --clean
      - name: Build and publish docs
        if: inputs.deploy
        run: uv run --no-sync mkdocs gh-deploy --force
